branch-defaults:
  master:
    environment: ExploratoryTestingGame
    group_suffix: null
global:
  application_name: ExploratoryTestingGame
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: eu-central-1
  profile: null
  sc: git
